name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy-frontend:
    if: contains(github.event.head_commit.modified, 'packages/nanlan-blog-client-nextjs/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.FRONTEND_PROJECT_ID }}
          working-directory: ./packages/nanlan-blog-client-nextjs

  deploy-backend:
    if: contains(github.event.head_commit.modified, 'packages/nanlan-blog-server-nestjs/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.BACKEND_PROJECT_ID }}
          working-directory: ./packages/nanlan-blog-server-nestjs
